# -*- coding: utf-8 -*-
"""Zona climatica(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mx82JeuidR9007Sf9SL37wFKaaATVH3b
"""

# CONFIGURACIÓN INICIAL
!pip install ipywidgets --quiet

import ipywidgets as widgets
from IPython.display import display

# Zonas
zonas_climaticas = {
    "Albacete": [
        (0, 450, "C3"),
        (451, 901, "D3"),
        (901, float('inf'), "E1")
    ],
    "Alicante": [
        (0, 250, "B4"),
        (251, 700, "C3"),
        (701, float('inf'), "D3")
    ],
    "Almeria":[
        (0, 100, "A4"),
        (101, 250, "B4"),
        (251, 400, "B3"),
        (401, 800, "C3"),
        (801, float('inf'), "D3")
    ],
        "Araba/Alava":[
        (0, 600, "D1"),
        (601, float('inf'), "E1")
    ],
    "Asturias":[
        (0, 50, "C1"),
        (51, 550, "D1"),
        (551, float('inf'), "E1")
    ],
     "Avila":[
        (0, 550, "D2"),
        (551, 850, "D1"),
        (851, float('inf'), "E1")
],
     "Badajoz":[
        (0, 400, "C4"),
        (401, 450, "C3"),
        (451, float('inf'), "D3")
],
     "Balears, llles":[
        (0, 250, "B3"),
        (251, float('inf'), "C3")
],
     "Barcelona":[
        (0, 250, "C2"),
        (251, 450, "D2"),
        (451, 750, "D1"),
        (751, float('inf'), "E1")
],
     "Bizkala":[
        (0, 250, "C1"),
        (251, float('inf'), "D1")
],
     "Burgos":[
        (0, 600, "D1"),
        (601, float('inf'), "E1")
],
     "Caceres":[
        (0, 600, "C4"),
        (601, 1050, "D3"),
        (1051, float('inf'), "E1")
],
     "Cadiz":[
        (0, 150, "A3"),
        (151, 450, "B3"),
        (451, 600, "C3"),
        (601, 850, "C2"),
        (851, float('inf'), "D2")
],
     "Cantabria":[
        (0, 150, "C1"),
        (151, 650, "D1"),
        (651, float('inf'), "E1")
],
     "Castellon":[
        (0, 100, "B3"),
        (101, 500, "C3"),
        (501, 600, "D3"),
        (601, 1000, "D2"),
        (1001, float('inf'), "E1")
],
     "Ceuta":[
        (0, float('inf'), "B3")
],
     "Ciudad real":[
        (0, 450, "C4"),
        (451, 500, "C3"),
        (501, float('inf'), "D3")
],
     "Cordoba":[
        (0, 150, "B4"),
        (151, 550, "C4"),
        (551, float('inf'), "D3")
],
     "Coruña":[
        (0, 200, "C1"),
        (201, float('inf'), "D1")
],
     "Cuenca":[
        (0, 800, "D3"),
        (801, 1050, "D2"),
        (1051, float('inf'), "E1")
],
     "Gipuzkoa":[
        (0, 400, "D1"),
        (401, float('inf'), "E1")
],
     "Girona":[
        (0, 100, "C2"),
        (101, 600, "D2"),
        (601, float('inf'), "E1")
],
     "Granada":[
        (0, 50, "A4"),
        (51, 350, "B4"),
        (351, 600, "C4"),
        (601, 800, "C3"),
        (801, 1300, "D3"),
        (1301, float('inf'), "E1")
],
     "Guadalajara":[
        (0, 950, "D3"),
        (951, 1000, "D2"),
        (1001, float('inf'), "E1")
],
     "Huelva":[
        (0, 50, "A4"),
        (51, 150, "B4"),
        (151, 350, "B3"),
        (351, 800, "C3"),
        (1001, float('inf'), "D3")
],
     "Huesca":[
        (0, 200, "C3"),
        (201, 400, "D3"),
        (401, 700, "D2"),
        (701, float('inf'), "E1")
],
     "Jaen":[
        (0, 350, "B4"),
        (351, 750, "B4"),
        (751, 1250, "D3"),
        (1251, float('inf'), "E1")
],
     "Leon":[
        (0, float('inf'), "E1")
],
     "Lleida":[
        (0, 100, "C3"),
        (101, 600, "D3"),
        (601, float('inf'), "E1")
],
     "Lugo":[
        (0, 500, "D1"),
        (501, float('inf'), "E1")
],
     "Madrid":[
        (0, 500, "C3"),
        (501, 900, "D3"),
        (901, 950, "D2"),
        (951, float('inf'), "E1")
],
     "Malaga":[
        (0, 100, "A3"),
        (101, 300, "B3"),
        (301, 700, "C3"),
        (701, float('inf'), "D3")
],
     "Melilla":[
        (0, float('inf'), "A3")
],
     "Murcia":[
        (0, 100, "B3"),
        (101, 550, "C3"),
        (551, float('inf'), "D3")
],
     "Navarra":[
        (0, 100, "C2"),
        (101, 350, "D2"),
        (351, 600, "D1"),
        (601, float('inf'), "E1")
],
     "Ourense":[
        (0, 150, "C3"),
        (151, 300, "c2"),
        (301, 800, "D2"),
        (801, float('inf'), "E1")
],
     "Palencia":[
        (0, 800, "D1"),
        (801, float('inf'), "E1")
],
     "Palmas, Las":[
        (0, 350, "A3"),
        (351, 750, "A2"),
        (751, 1000, "B2"),
        (1001, float('inf'), "C2")
],
     "Pontevedra":[
        (0, 350, "C1"),
        (351, float('inf'), "D1")
],
     "Rioja, La":[
        (0, 200, "C2"),
        (201, 700, "D2"),
        (701, float('inf'), "E1")
],
     "Salamanca":[
        (0, 850, "D2"),
        (851, float('inf'), "E1")
],
     "Rioja, La":[
        (0, 200, "C2"),
        (201, 700, "D2"),
        (701, float('inf'), "E1")
],
     "Santa Cruz de Tenerife":[
        (0, 350, "A3"),
        (351, 750, "A2"),
        (751, 1000, "B2"),
        (1001, float('inf'), "C2")
],
     "Segovia":[
        (0, 1050, "D2"),
        (1051, float('inf'), "E1")
],
     "Sevilla":[
        (0, 200, "B4"),
        (201, float('inf'), "C4")
],
     "Soria":[
        (0, 750, "D2"),
        (751, 800, "D1"),
        (801, float('inf'), "E1")
],
     "Tarragona":[
        (0, 100, "B3"),
        (101, 500, "C3"),
        (501, float('inf'), "D3")
],
     "Teruel":[
        (0, 450, "C3"),
        (451, 500, "C2"),
        (501, 1000, "D2"),
        (1001, float('inf'), "E1")
],
     "Toledo":[
        (0, 500, "C4"),
        (501, float('inf'), "D3")
],
     "Valencia":[
        (0, 50, "B3"),
        (51, 500, "C3"),
        (501, 950, "D2"),
        (951, float('inf'), "E1")
],
     "Valladolid":[
        (0, 800, "D2"),
        (801, float('inf'), "E1")
],
     "Zamora":[
        (0, 800, "D2"),
        (801, float('inf'), "E1")
],
     "Zaragoza":[
        (0, 200, "C3"),
        (201, 650, "D3"),
        (651, float('inf'), "E1")
        ]
}

# Busqueda
def obtener_zona_climatica(provincia, altitud):
    rangos = zonas_climaticas.get(provincia)
    if not rangos:
        return f"Provincia '{provincia}' no disponible."

    for min_alt, max_alt, zona in rangos:
        if min_alt <= altitud <= max_alt:
            return f"🔎 Zona climática para {provincia} a {altitud} m: {zona}"
    return "No se encontró una zona climática para esa altitud."

# Widgets interactivos
provincia_dropdown = widgets.Dropdown(
    options=list(zonas_climaticas.keys()),
    description='Provincia:',
    style={'description_width': 'initial'}
)

altitud_input = widgets.IntSlider(
    value=100,
    min=0,
    max=2000,
    step=10,
    description='Altitud (m):',
    style={'description_width': 'initial'},
    continuous_update=False
)

output = widgets.Output()

def actualizar_resultado(change=None):
    output.clear_output()
    with output:
        provincia = provincia_dropdown.value
        altitud = altitud_input.value
        print(obtener_zona_climatica(provincia, altitud))

provincia_dropdown.observe(actualizar_resultado, names='value')
altitud_input.observe(actualizar_resultado, names='value')

# Resultado
display(provincia_dropdown, altitud_input, output)
actualizar_resultado()